---

- name: 'Download Wordpress'
  get_url:
    url: 'https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Extract Archive'
  ansible.builtin.unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www'
    remote_src: yes

- name: 'Change file ownership'
  ansible.builtin.file:
    path: '/var/www/wordpress'
    owner: 'www-data'
    group: 'www-data'
    mode: 700
